[toolchain]
anchor_version = "1.1.2"
solana_version = "2.1.5"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rift_token = "GdTffSB1aNxfCeZW3PG2S7c788DnZgduJ68jWak3aJrp"
ultra_core_rift = "CBrsXBaa1DTHFdCwCkeQHm3bQKRFaWfPx6bKNmM5r5uy"

[programs.localnet]
rift_token = "G54ub1p1SLho4JXF6kDJzu3WaBCN6YLYF8QgjjG3noZy"
ultra_core_rift = "6cTGeWKXiZHRQBMqvv4Ce3E8YXX4g456rN7JnuKdELmo"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/ultra_core_rift", "programs/rift_token"]

[hooks]
