[package]
name = "rift_token"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-security-txt = "1.1.1"
anchor-lang = { version = "0.30.0", features = ["init-if-needed"] }
anchor-spl = "0.30.0"

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]


[lib]
crate-type = ["cdylib", "lib"]
