import * as anchor from "@coral-xyz/anchor";
import { Program, AnchorProvider, BN } from "@coral-xyz/anchor";
import { Connection, Keypair, PublicKey, SystemProgram, Transaction } from "@solana/web3.js";
import { TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID, getAssociatedTokenAddressSync, createAssociatedTokenAccountInstruction, createInitializeMintInstruction, MINT_SIZE, getMinimumBalanceForRentExemptMint } from "@solana/spl-token";
import fs from "fs"; import path from "path"; import os from "os";
const idPath = path.join(os.homedir(), ".config", "solana", "id.json");
const wallet = Keypair.fromSecretKey(new Uint8Array(JSON.parse(fs.readFileSync(idPath, "utf-8"))));
const connection = new Connection("http://127.0.0.1:8899", "confirmed");
const provider = new AnchorProvider(connection, new anchor.Wallet(wallet), { commitment: "confirmed" });
anchor.setProvider(provider);
const ULTRA = new PublicKey("45oaP6nFPqCNcd6zcTXHLFNYdujNDHyKiNdDQQ4H4arM");
const RIFT = new PublicKey("6zXnKoRT9B46JAVVBktCkgGWRJhcPsfyMX9NwR67q64x");
const uIdl = JSON.parse(fs.readFileSync("target/idl/ultra_core_rift.json", "utf-8")); uIdl.address = ULTRA.toBase58();
const tIdl = JSON.parse(fs.readFileSync("target/idl/rift_token.json", "utf-8")); tIdl.address = RIFT.toBase58();
const uProg = new Program(uIdl as any, provider);
const tProg = new Program(tIdl as any, provider);
async function main() {
  console.log("Wallet:", wallet.publicKey.toBase58());
  const coreState = Keypair.generate();
  console.log("CoreState:", coreState.publicKey.toBase58());
  await (uProg.methods as any).initialize(wallet.publicKey).accounts({ coreState: coreState.publicKey, payer: wallet.publicKey, systemProgram: SystemProgram.programId }).signers([coreState]).rpc();
  console.log("CoreState initialized");
  const [rts] = PublicKey.findProgramAddressSync([Buffer.from("rift_token_state")], RIFT);
  const [ra] = PublicKey.findProgramAddressSync([Buffer.from("rift_mint_authority")], RIFT);
  console.log("RiftTokenState:", rts.toBase58(), "RiftAuthority:", ra.toBase58());
  const mint = Keypair.generate(); console.log("Mint:", mint.publicKey.toBase58());
  const rent = await getMinimumBalanceForRentExemptMint(connection);
  await provider.sendAndConfirm(new Transaction().add(SystemProgram.createAccount({ fromPubkey: wallet.publicKey, newAccountPubkey: mint.publicKey, space: MINT_SIZE, lamports: rent, programId: TOKEN_PROGRAM_ID }), createInitializeMintInstruction(mint.publicKey, 9, ra, null, TOKEN_PROGRAM_ID)), [mint]);
  console.log("Mint created");
  const av = getAssociatedTokenAddressSync(mint.publicKey, wallet.publicKey);
  await provider.sendAndConfirm(new Transaction().add(createAssociatedTokenAccountInstruction(wallet.publicKey, av, wallet.publicKey, mint.publicKey, TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID)));
  console.log("Admin Vault ATA:", av.toBase58());
  await (tProg.methods as any).initialize(9, 10, new BN("1000000000000")).accounts({ riftTokenState: rts, coreState: coreState.publicKey, riftMint: mint.publicKey, adminVaultTokenAccount: av, adminVault: wallet.publicKey, riftAuthority: ra, gate: wallet.publicKey, tokenProgram: TOKEN_PROGRAM_ID, systemProgram: SystemProgram.programId }).rpc();
  console.log("RiftToken initialized");
  console.log("SAVE THESE:");
  console.log("CoreState:", coreState.publicKey.toBase58());
  console.log("RiftTokenState:", rts.toBase58());
  console.log("RiftMint:", mint.publicKey.toBase58());
  console.log("AdminVaultATA:", av.toBase58());
}
main().catch(console.error);
